name: container_ci

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  schedule:
    - cron: "0 2 * * 0" # Weekly on Sundays at 02:00

jobs:
  container_ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
      image: moveit/moveit2:foxy-source
    steps:
      - name: Build Workspace
        run: |
          . /opt/ros/foxy/setup.sh
          mkdir -p $GITHUB_WORKSPACE/ros2_ws/src
          cd $GITHUB_WORKSPACE/ros2_ws
          colcon build
      - name: Checkout clane_plus
        uses: actions/checkout@v2
        with:
          path: ros2_ws/src/crane_plus
      - name: Build crane_plus 
        run: |
          . /opt/ros/foxy/setup.sh
          . /root/ws_moveit/install/setup.sh
          cd $GITHUB_WORKSPACE/ros2_ws/src
          apt update
          rosdep update
          rosdep install -r -y -i --from-paths .
          cd ..
          colcon build
      - name: Test
        run: |
          . /opt/ros/foxy/setup.sh
          . /root/ws_moveit/install/setup.sh
          . $GITHUB_WORKSPACE/ros2_ws/install/setup.sh
          cd $GITHUB_WORKSPACE/ros2_ws
          colcon test
          colcon test-result --verbose
